### ISSUE TITLE
Route [tracy.bar] not defined

### ISSUE THREAD

**Issue by jyhsu2000** [HackerSir/CheckIn#99]
環境設定為以下時
```properties
APP_ENV=production
APP_DEBUG=true
```
會出現
```
Stack trace:
#0 /srv/http/CheckIn/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(319): Illuminate\Routing\UrlGenerator->route('tracy.bar')
#1 /srv/http/CheckIn/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(304): Recca0120\LaravelTracy\DebuggerManager->replacePath('<!DOCTYPE html>...')
#2 /srv/http/CheckIn/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(232): Recca0120\LaravelTracy\DebuggerManager->renderBuffer(Object(Closure))
#3 /srv/http/CheckIn/vendor/recca0120/laravel-tracy/src/Exceptions/Handler.php(65): Recca0120\LaravelTracy\DebuggerManager->exceptionHandler(Object(InvalidArgumentException))
#4 /srv/http/CheckIn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Recca0120\LaravelTracy\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#5 /srv/http {"userId":1,"email":"jyhsu2000@gmail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught InvalidArgumentException: Route [tracy.bar] not defined. in /srv/http/CheckIn/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:372
Stack trace:
#0 /srv/http/CheckIn/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(319): Illuminate\\Routing\\UrlGenerator->route('tracy.bar')
#1 /srv/http/CheckIn/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(304): Recca0120\\LaravelTracy\\DebuggerManager->replacePath('<!DOCTYPE html>...')
#2 /srv/http/CheckIn/vendor/recca0120/laravel-tracy/src/DebuggerManager.php(232): Recca0120\\LaravelTracy\\DebuggerManager->renderBuffer(Object(Closure))
#3 /srv/http/CheckIn/vendor/recca0120/laravel-tracy/src/Exceptions/Handler.php(65): Recca0120\\LaravelTracy\\DebuggerManager->exceptionHandler(Object(InvalidArgumentException))
#4 /srv/http/CheckIn/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(112): Recca0120\\LaravelTracy\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#5 /srv/http at /srv/http/CheckIn/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:372)
[stacktrace]
#0 {main}
"}
```
tracy 中的相關設定為
```php
'enabled'       => env('APP_DEBUG') === true,
'showBar'       => env('APP_ENV') !== 'production',
```
可能有些關聯

**Comment by danny50610** [comment]
更新許多套件後，好像沒有出現了

**Comment by jyhsu2000** [comment]
實測確認問題已消失
